defmodule Camelot.Repo.Migrations.AddPrCommentsSeenAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :pr_comments_seen_at, :utc_datetime
    end
  end

  def down do
    alter table(:tasks) do
      remove :pr_comments_seen_at
    end
  end
end
