defmodule Camelot.Repo.Migrations.GithubAppToUserScope do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      remove :github_installation_id
    end

    # Clean cutover: installations move from project scope to user
    # scope and no backfill is done, so existing rows have no user to
    # attach to. Affected users reconnect GitHub from their profile,
    # which re-upserts a fresh row via the webhook/setup flow.
    execute("DELETE FROM github_installations")

    alter table(:github_installations) do
      add :user_id,
          references(:users,
            column: :id,
            name: "github_installations_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:github_installations, "github_installations_user_id_fkey")

    alter table(:github_installations) do
      remove :user_id
    end

    alter table(:projects) do
      add :github_installation_id,
          references(:github_installations,
            column: :id,
            name: "projects_github_installation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end
end
