defmodule Camelot.Repo.Migrations.AddTaskRunnerHandle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :runner_handle, :text
    end
  end

  def down do
    alter table(:tasks) do
      remove :runner_handle
    end
  end
end
