defmodule Camelot.Repo.Migrations.RenameAgentTemplateToAgent do
  @moduledoc """
  Decommissions the "Agents" tab: the per-project runtime `Agent` row
  (name, status, `*_override` fields, `project_id`/`user_id`/
  `template_id`) disappears entirely. `AgentTemplate` becomes the new
  `Agent` (the "Agent CLI" a task picks at creation time) and gains
  `max_retries`; the seven `*_override` fields move to `Project`.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  and then hand-edited: the generator diffs by table name, and since
  the renamed `Agent` resource keeps targeting table `agents` (freed up
  by deleting the old runtime resource), it saw an in-place attribute
  diff on `agents` instead of the actual transition — drop the old
  `agents` table, rename `agent_templates` to `agents`. Historical
  `agent_id` FKs on `tasks`/`sessions`/`env_vars` point at old runtime
  rows and must be remapped to their `template_id` before the old
  `agents` table is dropped, or that history is lost.
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :command_prefix_override, :text
      add :executable_override, :text
      add :base_args_override, {:array, :text}
      add :env_vars_override, :map
      add :permission_args_by_stage_override, :map
      add :internal_tools_override, {:array, :text}
      add :base_retry_delay_ms_override, :bigint
    end

    alter table(:agent_templates) do
      add :max_retries, :bigint, null: false, default: 3
    end

    # The `agent_id` columns on tasks/sessions/env_vars still FK to the
    # old runtime `agents` rows. Remapping them to `template_id` (an
    # `agent_templates` id, absent from the old `agents` table) would
    # violate those constraints mid-migration, so drop the referencing
    # FKs first; they're re-added at the end pointing at the renamed
    # `agents` table. (The later `DROP TABLE agents CASCADE` would also
    # drop them, but only after these UPDATEs — too late.)
    execute("ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_agent_id_fkey")
    execute("ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_agent_id_fkey")
    execute("ALTER TABLE env_vars DROP CONSTRAINT IF EXISTS env_vars_agent_id_fkey")

    # Remap FKs off the old `agents` table before it's dropped: those
    # columns currently point at per-project runtime Agent rows, not
    # templates.
    execute("""
    UPDATE tasks
       SET agent_id = a.template_id
      FROM agents a
     WHERE tasks.agent_id = a.id
    """)

    execute("""
    UPDATE sessions
       SET agent_id = a.template_id
      FROM agents a
     WHERE sessions.agent_id = a.id
    """)

    execute("""
    UPDATE env_vars
       SET agent_id = a.template_id
      FROM agents a
     WHERE env_vars.agent_id = a.id
    """)

    # CASCADE drops agents_project_id_fkey/agents_user_id_fkey/
    # agents_template_id_fkey (owned by this table). The
    # tasks/sessions/env_vars referencing FKs were already dropped above.
    execute("DROP TABLE agents CASCADE")

    rename table(:agent_templates), to: table(:agents)
    execute("ALTER INDEX agent_templates_unique_slug_index RENAME TO agents_unique_slug_index")

    execute("""
    ALTER TABLE tasks
      ADD CONSTRAINT tasks_agent_id_fkey
      FOREIGN KEY (agent_id) REFERENCES agents(id)
    """)

    execute("""
    ALTER TABLE sessions
      ADD CONSTRAINT sessions_agent_id_fkey
      FOREIGN KEY (agent_id) REFERENCES agents(id)
    """)

    execute("""
    ALTER TABLE env_vars
      ADD CONSTRAINT env_vars_agent_id_fkey
      FOREIGN KEY (agent_id) REFERENCES agents(id)
    """)
  end

  # Best-effort reverse: restores the table shapes, but the per-project
  # runtime `agents` rows (name/status/project/user/overrides) dropped
  # by `up` cannot be reconstructed, and `tasks`/`sessions`/`env_vars`
  # `agent_id` values have already been remapped to template ids — so
  # the FKs from those tables are deliberately NOT re-pointed at the
  # recreated (empty) `agents` table, since none of that data would
  # satisfy referential integrity against it.
  def down do
    execute("ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_agent_id_fkey")
    execute("ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_agent_id_fkey")
    execute("ALTER TABLE env_vars DROP CONSTRAINT IF EXISTS env_vars_agent_id_fkey")

    execute("ALTER INDEX agents_unique_slug_index RENAME TO agent_templates_unique_slug_index")
    rename table(:agents), to: table(:agent_templates)

    alter table(:agent_templates) do
      remove :max_retries
    end

    alter table(:projects) do
      remove :base_retry_delay_ms_override
      remove :internal_tools_override
      remove :permission_args_by_stage_override
      remove :env_vars_override
      remove :base_args_override
      remove :executable_override
      remove :command_prefix_override
    end

    create table(:agents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :status, :text, null: false, default: "idle"
      add :max_retries, :bigint, null: false, default: 3
      add :command_prefix_override, :text
      add :executable_override, :text
      add :base_args_override, {:array, :text}
      add :env_vars_override, :map
      add :permission_args_by_stage_override, :map
      add :internal_tools_override, {:array, :text}
      add :base_retry_delay_ms_override, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "agents_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "agents_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :template_id,
          references(:agent_templates,
            column: :id,
            name: "agents_template_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:agents, [:project_id, :user_id, :template_id],
             name: "agents_unique_project_user_template_index"
           )
  end
end
