defmodule Camelot.Repo.Migrations.AddPromptTemplates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:prompt_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text, null: false
      add :name, :text, null: false
      add :body, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "prompt_templates_project_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:prompt_templates, [:slug, :project_id],
             name: "prompt_templates_unique_slug_per_scope_index"
           )
  end

  def down do
    drop_if_exists unique_index(:prompt_templates, [:slug, :project_id],
                     name: "prompt_templates_unique_slug_per_scope_index"
                   )

    drop constraint(:prompt_templates, "prompt_templates_project_id_fkey")

    drop table(:prompt_templates)
  end
end
