defmodule Camelot.Repo.Migrations.AddUsageLimitPause do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :notify_on_usage_limit_paused, :boolean, null: false, default: true
      add :notify_on_usage_limit_resumed, :boolean, null: false, default: true
    end

    alter table(:tasks) do
      add :paused_until, :utc_datetime_usec
      add :pause_reason, :text
    end

    alter table(:credentials) do
      add :usage_limited_until, :utc_datetime_usec
      add :usage_limit_window, :text
    end
  end

  def down do
    alter table(:credentials) do
      remove :usage_limit_window
      remove :usage_limited_until
    end

    alter table(:tasks) do
      remove :pause_reason
      remove :paused_until
    end

    alter table(:users) do
      remove :notify_on_usage_limit_resumed
      remove :notify_on_usage_limit_paused
    end
  end
end
