defmodule Camelot.Repo.Migrations.AddNotificationPreferences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :notify_on_waiting_for_input, :boolean, null: false, default: true
      add :notify_on_error, :boolean, null: false, default: true
      add :notify_on_done, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:users) do
      remove :notify_on_done
      remove :notify_on_error
      remove :notify_on_waiting_for_input
    end
  end
end
