defmodule Camelot.Repo.Migrations.AddSessionRunStats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      add :cost_usd, :float
      add :duration_ms, :bigint
      add :duration_api_ms, :bigint
      add :num_turns, :bigint
      add :usage, :map
    end
  end

  def down do
    alter table(:sessions) do
      remove :usage
      remove :num_turns
      remove :duration_api_ms
      remove :duration_ms
      remove :cost_usd
    end
  end
end
