defmodule Camelot.Repo.Migrations.AddSessionClarified do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      add :clarified, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:sessions) do
      remove :clarified
    end
  end
end
