defmodule Camelot.Repo.Migrations.AddEnvVars do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:env_vars, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :secret, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "env_vars_project_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :agent_id,
          references(:agents,
            column: :id,
            name: "env_vars_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :user_id,
          references(:users,
            column: :id,
            name: "env_vars_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :encrypted_value, :binary, null: false
    end

    create unique_index(:env_vars, [:key, :agent_id],
             name: "env_vars_unique_agent_key_index",
             where: "(agent_id IS NOT NULL)"
           )

    create unique_index(:env_vars, [:key],
             name: "env_vars_unique_global_key_index",
             where: "(project_id IS NULL AND agent_id IS NULL AND user_id IS NULL)"
           )

    create unique_index(:env_vars, [:key, :project_id],
             name: "env_vars_unique_project_key_index",
             where: "(project_id IS NOT NULL)"
           )

    create unique_index(:env_vars, [:key, :user_id],
             name: "env_vars_unique_user_key_index",
             where: "(user_id IS NOT NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:env_vars, [:key, :user_id],
                     name: "env_vars_unique_user_key_index"
                   )

    drop_if_exists unique_index(:env_vars, [:key, :project_id],
                     name: "env_vars_unique_project_key_index"
                   )

    drop_if_exists unique_index(:env_vars, [:key], name: "env_vars_unique_global_key_index")

    drop_if_exists unique_index(:env_vars, [:key, :agent_id],
                     name: "env_vars_unique_agent_key_index"
                   )

    drop constraint(:env_vars, "env_vars_project_id_fkey")

    drop constraint(:env_vars, "env_vars_agent_id_fkey")

    drop constraint(:env_vars, "env_vars_user_id_fkey")

    drop table(:env_vars)
  end
end
