defmodule Camelot.Repo.Migrations.AddUserOnboardingTimestamps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :onboarding_dismissed_at, :utc_datetime_usec
      add :onboarding_completed_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:users) do
      remove :onboarding_completed_at
      remove :onboarding_dismissed_at
    end
  end
end
