defmodule Camelot.Repo.Migrations.AddGithubAppIntegration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :github_installation_id, :uuid
    end

    create table(:github_installations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:projects) do
      modify :github_installation_id,
             references(:github_installations,
               column: :id,
               name: "projects_github_installation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:github_installations) do
      add :installation_id, :bigint, null: false
      add :account_login, :text, null: false
      add :account_type, :text, null: false
      add :suspended_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:github_installations, [:installation_id],
             name: "github_installations_unique_installation_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:github_installations, [:installation_id],
                     name: "github_installations_unique_installation_id_index"
                   )

    alter table(:github_installations) do
      remove :updated_at
      remove :inserted_at
      remove :suspended_at
      remove :account_type
      remove :account_login
      remove :installation_id
    end

    drop constraint(:projects, "projects_github_installation_id_fkey")

    alter table(:projects) do
      modify :github_installation_id, :uuid
    end

    drop table(:github_installations)

    alter table(:projects) do
      remove :github_installation_id
    end
  end
end
