defmodule Camelot.Repo.Migrations.AddAgentTemplates do
  @moduledoc """
  Introduce the `agent_templates` table that holds the CLI
  shape and parser choice for each agent type, replace the
  hardcoded `agents.type` atom enum with a `template_id`
  FK, and add nullable `*_override` columns on `agents`
  for per-project tweaks.

  Existing rows are backfilled from `agents.type` to the
  matching seeded template before the column is dropped.

  This file was autogenerated with
  `mix ash_postgres.generate_migrations` and then hand-edited
  to order schema/data steps for a safe in-place backfill.
  """

  use Ecto.Migration

  @pr_url_pattern "https://github\\.com/[^\\s]+/pull/(\\d+)"
  @question_phrases [
    "could you",
    "can you",
    "please provide",
    "please clarify",
    "please specify",
    "what would",
    "which approach",
    "do you want",
    "would you like",
    "waiting for",
    "need more information",
    "let me know"
  ]

  def up do
    create table(:agent_templates, primary_key: false) do
      add :id, :uuid,
        null: false,
        default: fragment("gen_random_uuid()"),
        primary_key: true

      add :slug, :text, null: false
      add :name, :text, null: false
      add :command_prefix, :text
      add :executable, :text, null: false
      add :base_args, {:array, :text}, null: false, default: []
      add :prompt_flag, :text
      add :tools_flag, :text
      add :tools_separator, :text, null: false, default: ","
      add :permission_args_by_stage, :map, null: false, default: %{}
      add :internal_tools, {:array, :text}, null: false, default: []
      add :env_vars, :map, null: false, default: %{}
      add :parser, :text, null: false, default: "raw_text"

      add :pr_url_pattern, :text,
        null: false,
        default: "https://github\\.com/[^\\s]+/pull/(\\d+)"

      add :question_phrases, {:array, :text}, null: false, default: []
      add :base_retry_delay_ms, :bigint, null: false, default: 5_000

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:agent_templates, [:slug], name: "agent_templates_unique_slug_index")

    seed_claude_code_template()
    seed_codex_template()

    alter table(:agents) do
      add :template_id, :uuid
      add :command_prefix_override, :text
      add :executable_override, :text
      add :base_args_override, {:array, :text}
      add :env_vars_override, :map
      add :permission_args_by_stage_override, :map
      add :internal_tools_override, {:array, :text}
      add :base_retry_delay_ms_override, :bigint
    end

    execute("""
    UPDATE agents
       SET template_id = t.id
      FROM agent_templates t
     WHERE t.slug = agents.type
    """)

    alter table(:agents) do
      modify :template_id,
             references(:agent_templates,
               column: :id,
               name: "agents_template_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: false

      remove :type
    end
  end

  def down do
    alter table(:agents) do
      add :type, :text
    end

    execute("""
    UPDATE agents
       SET type = t.slug
      FROM agent_templates t
     WHERE t.id = agents.template_id
    """)

    drop constraint(:agents, "agents_template_id_fkey")

    alter table(:agents) do
      remove :template_id
      remove :base_retry_delay_ms_override
      remove :internal_tools_override
      remove :permission_args_by_stage_override
      remove :env_vars_override
      remove :base_args_override
      remove :executable_override
      remove :command_prefix_override
    end

    drop_if_exists unique_index(:agent_templates, [:slug],
                     name: "agent_templates_unique_slug_index"
                   )

    drop table(:agent_templates)
  end

  defp seed_claude_code_template do
    permission_map = %{
      "planning" => ["--permission-mode", "plan"],
      "executing" => ["--permission-mode", "acceptEdits"]
    }

    execute("""
    INSERT INTO agent_templates (
      slug, name, command_prefix, executable, base_args,
      prompt_flag, tools_flag, tools_separator,
      permission_args_by_stage, internal_tools, env_vars,
      parser, pr_url_pattern, question_phrases,
      base_retry_delay_ms
    )
    VALUES (
      'claude_code', 'Claude Code', NULL, 'claude',
      ARRAY['--output-format','json']::text[],
      '-p', '--allowedTools', ',',
      #{quote_jsonb(permission_map)},
      ARRAY['EnterPlanMode','ExitPlanMode']::text[],
      #{quote_jsonb(%{"CLAUDECODE" => "false"})},
      'claude_code_json',
      #{quote_str(@pr_url_pattern)},
      #{quote_text_array(@question_phrases)},
      5000
    )
    ON CONFLICT (slug) DO NOTHING
    """)
  end

  defp seed_codex_template do
    execute("""
    INSERT INTO agent_templates (
      slug, name, command_prefix, executable, base_args,
      prompt_flag, tools_flag, tools_separator,
      permission_args_by_stage, internal_tools, env_vars,
      parser, pr_url_pattern, question_phrases,
      base_retry_delay_ms
    )
    VALUES (
      'codex', 'Codex', NULL, 'codex',
      ARRAY['--quiet']::text[],
      NULL, NULL, ',',
      '{}'::jsonb,
      ARRAY[]::text[],
      '{}'::jsonb,
      'raw_text',
      #{quote_str(@pr_url_pattern)},
      ARRAY[]::text[],
      5000
    )
    ON CONFLICT (slug) DO NOTHING
    """)
  end

  defp quote_str(s) do
    "'" <> String.replace(s, "'", "''") <> "'"
  end

  defp quote_jsonb(map) do
    quote_str(Jason.encode!(map)) <> "::jsonb"
  end

  defp quote_text_array(list) do
    inner =
      list
      |> Enum.map(&quote_str/1)
      |> Enum.join(",")

    "ARRAY[#{inner}]::text[]"
  end
end
