defmodule Camelot.Repo.Migrations.AddSwarmNodePins do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:system_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false, default: "singleton"
      add :default_swarm_node_label, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:system_settings, [:key], name: "system_settings_singleton_index")

    alter table(:projects) do
      add :swarm_node_label, :text
    end
  end

  def down do
    alter table(:projects) do
      remove :swarm_node_label
    end

    drop_if_exists unique_index(:system_settings, [:key], name: "system_settings_singleton_index")

    drop table(:system_settings)
  end
end
