defmodule Camelot.Repo.Migrations.AddPromptTemplateUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:prompt_templates) do
      add :user_id,
          references(:users,
            column: :id,
            name: "prompt_templates_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop_if_exists unique_index(:prompt_templates, [:slug, :project_id],
                     name: "prompt_templates_unique_slug_per_scope_index"
                   )

    create unique_index(:prompt_templates, [:slug, :project_id, :user_id],
             name: "prompt_templates_unique_slug_per_scope_index"
           )
  end

  def down do
    drop_if_exists unique_index(:prompt_templates, [:slug, :project_id, :user_id],
                     name: "prompt_templates_unique_slug_per_scope_index"
                   )

    create unique_index(:prompt_templates, [:slug, :project_id],
             name: "prompt_templates_unique_slug_per_scope_index"
           )

    drop constraint(:prompt_templates, "prompt_templates_user_id_fkey")

    alter table(:prompt_templates) do
      remove :user_id
    end
  end
end
