defmodule Camelot.Repo.Migrations.AddRunnerResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :swarm_node_label, :text
    end

    alter table(:sessions) do
      modify :task_id, :uuid, null: true
      modify :status, :text, default: "queued"
      add :kind, :text, null: false, default: "task"
      add :bootstrap_kind, :text
      add :queued_at, :utc_datetime
      add :service_id, :text
      add :was_adopted, :boolean, null: false, default: false

      add :user_id,
          references(:users,
            column: :id,
            name: "sessions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:projects) do
      add :git_url, :text
    end

    drop_if_exists unique_index(:projects, [:path], name: "projects_unique_path_index")

    alter table(:projects) do
      modify :path, :text, null: true
    end

    create table(:project_memberships, primary_key: false) do
      add :role, :text, null: false, default: "member"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "project_memberships_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "project_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false
    end

    create table(:project_mcps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :command, :text, null: false
      add :args, {:array, :text}, null: false, default: []
      add :env, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "project_mcps_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:project_mcps, [:project_id, :name],
             name: "project_mcps_unique_name_per_project_index"
           )

    create table(:credentials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :name, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "credentials_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :encrypted_value, :binary, null: false
    end

    create unique_index(:credentials, [:user_id, :kind, :name],
             name: "credentials_unique_kind_per_user_index"
           )

    alter table(:agents) do
      add :user_id,
          references(:users,
            column: :id,
            name: "agents_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop_if_exists unique_index(:agents, [:project_id], name: "agents_unique_project_index")

    create unique_index(:agents, [:project_id, :user_id, :template_id],
             name: "agents_unique_project_user_template_index"
           )

    alter table(:agent_templates) do
      add :runner_image, :text
      add :runner_resources, :map, null: false, default: %{}
      add :required_credential_kinds, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:agent_templates) do
      remove :required_credential_kinds
      remove :runner_resources
      remove :runner_image
    end

    drop_if_exists unique_index(:agents, [:project_id, :user_id, :template_id],
                     name: "agents_unique_project_user_template_index"
                   )

    create unique_index(:agents, [:project_id], name: "agents_unique_project_index")

    drop constraint(:agents, "agents_user_id_fkey")

    alter table(:agents) do
      remove :user_id
    end

    drop_if_exists unique_index(:credentials, [:user_id, :kind, :name],
                     name: "credentials_unique_kind_per_user_index"
                   )

    drop constraint(:credentials, "credentials_user_id_fkey")

    drop table(:credentials)

    drop_if_exists unique_index(:project_mcps, [:project_id, :name],
                     name: "project_mcps_unique_name_per_project_index"
                   )

    drop constraint(:project_mcps, "project_mcps_project_id_fkey")

    drop table(:project_mcps)

    drop constraint(:project_memberships, "project_memberships_project_id_fkey")

    drop constraint(:project_memberships, "project_memberships_user_id_fkey")

    drop table(:project_memberships)

    alter table(:projects) do
      modify :path, :text, null: false
    end

    create unique_index(:projects, [:path], name: "projects_unique_path_index")

    alter table(:projects) do
      remove :git_url
    end

    drop constraint(:sessions, "sessions_user_id_fkey")

    alter table(:sessions) do
      remove :user_id
      remove :was_adopted
      remove :service_id
      remove :queued_at
      remove :bootstrap_kind
      remove :kind
      modify :status, :text, default: "running"
      modify :task_id, :uuid, null: false
    end

    alter table(:users) do
      remove :swarm_node_label
    end
  end
end
