defmodule Camelot.Repo.Migrations.AddLastErrorToTasks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :last_error, :text
    end
  end

  def down do
    alter table(:tasks) do
      remove :last_error
    end
  end
end
