defmodule Camelot.Repo.Migrations.AddTaskInterruptRequeues do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :interrupt_requeues, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:tasks) do
      remove :interrupt_requeues
    end
  end
end
