defmodule Camelot.Repo.Migrations.AddModelSelection do
  @moduledoc """
  Adds the "model selection" columns: `tasks.next_model` (the user's
  sticky, explicit choice for the next dispatch), `sessions.model`
  (the model a run actually used), and the `agents` columns an admin
  configures per CLI (`model_flag`, `available_models`,
  `default_model`).

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  and then hand-edited to seed `model_flag` (plus `available_models`/
  `default_model` for `claude_code`, whose model ids are confirmed)
  onto the seeded `claude_code`/`codex` rows — matching the
  reconciliation pattern used by prior data migrations (e.g.
  `claude_stream_json_base_args`). Only rewrites rows still carrying
  `model_flag IS NULL` so a hand-customised agent CLI is left untouched.
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :next_model, :text
    end

    alter table(:sessions) do
      add :model, :text
    end

    alter table(:agents) do
      add :model_flag, :text
      add :available_models, {:array, :text}, null: false, default: []
      add :default_model, :text
    end

    seed_claude_code_models()
    seed_codex_models()
  end

  def down do
    alter table(:agents) do
      remove :default_model
      remove :available_models
      remove :model_flag
    end

    alter table(:sessions) do
      remove :model
    end

    alter table(:tasks) do
      remove :next_model
    end
  end

  defp seed_claude_code_models do
    execute("""
    UPDATE agents
       SET model_flag = '--model',
           available_models = ARRAY[
             'claude-opus-5',
             'claude-sonnet-5',
             'claude-haiku-4-5-20251001'
           ]::text[],
           default_model = 'claude-sonnet-5'
     WHERE slug = 'claude_code' AND model_flag IS NULL
    """)
  end

  # `available_models`/`default_model` are deliberately left unset here:
  # unlike Claude Code's ids above, Codex CLI's current `--model` values
  # aren't confirmed. Left for an admin to fill in via the Agent CLI
  # admin page once verified against the CLI's own docs.
  defp seed_codex_models do
    execute("""
    UPDATE agents
       SET model_flag = '--model'
     WHERE slug = 'codex' AND model_flag IS NULL
    """)
  end
end
