defmodule Camelot.Repo.Migrations.AddProjectRunnerImageOverride do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :runner_image_override, :text
    end
  end

  def down do
    alter table(:projects) do
      remove :runner_image_override
    end
  end
end
