defmodule Camelot.Repo.Migrations.AddAgentsAndTasks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :plan, :text
      add :pr_url, :text
      add :pr_number, :bigint
      add :priority, :bigint, null: false, default: 0
      add :status, :text, null: false, default: "created"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "tasks_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :agent_id, :uuid
      add :creator_id, :uuid, null: false
    end

    create table(:sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "running"
      add :started_at, :utc_datetime
      add :finished_at, :utc_datetime
      add :output_log, :text
      add :exit_code, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :agent_id, :uuid, null: false
      add :task_id, :uuid, null: false
    end

    create table(:agents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:tasks) do
      modify :agent_id,
             references(:agents,
               column: :id,
               name: "tasks_agent_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :creator_id,
             references(:users,
               column: :id,
               name: "tasks_creator_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:sessions) do
      modify :agent_id,
             references(:agents,
               column: :id,
               name: "sessions_agent_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :task_id,
             references(:tasks,
               column: :id,
               name: "sessions_task_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:agents) do
      add :name, :text, null: false
      add :type, :text, null: false
      add :status, :text, null: false, default: "idle"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "agents_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:agents, [:project_id], name: "agents_unique_project_index")
  end

  def down do
    drop_if_exists unique_index(:agents, [:project_id], name: "agents_unique_project_index")

    drop constraint(:agents, "agents_project_id_fkey")

    alter table(:agents) do
      remove :project_id
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :type
      remove :name
    end

    drop constraint(:sessions, "sessions_agent_id_fkey")

    drop constraint(:sessions, "sessions_task_id_fkey")

    alter table(:sessions) do
      modify :task_id, :uuid
      modify :agent_id, :uuid
    end

    drop constraint(:tasks, "tasks_agent_id_fkey")

    drop constraint(:tasks, "tasks_creator_id_fkey")

    alter table(:tasks) do
      modify :creator_id, :uuid
      modify :agent_id, :uuid
    end

    drop table(:agents)

    drop table(:sessions)

    drop constraint(:tasks, "tasks_project_id_fkey")

    drop table(:tasks)
  end
end
