defmodule Camelot.Repo.Migrations.AddPreviousStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :previous_status, :text
    end
  end

  def down do
    alter table(:tasks) do
      remove :previous_status
    end
  end
end
