defmodule Camelot.Repo.Migrations.AddTaskFullPlan do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :full_plan, :text
    end
  end

  def down do
    alter table(:tasks) do
      remove :full_plan
    end
  end
end
