defmodule Camelot.Repo.Migrations.AddTaskLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:task_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :link_type, :text, null: false
      add :base_synced_sha, :text
      add :base_synced_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_task_id,
          references(:tasks,
            column: :id,
            name: "task_links_source_task_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :target_task_id,
          references(:tasks,
            column: :id,
            name: "task_links_target_task_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:task_links, [:source_task_id])

    create index(:task_links, [:target_task_id])

    create unique_index(:task_links, [:source_task_id, :target_task_id, :link_type],
             name: "task_links_unique_link_index"
           )

    create unique_index(:task_links, [:target_task_id],
             name: "task_links_unique_parent_index",
             where: "(link_type = 'parent_of')"
           )
  end

  def down do
    drop_if_exists unique_index(:task_links, [:target_task_id],
                     name: "task_links_unique_parent_index"
                   )

    drop_if_exists unique_index(:task_links, [:source_task_id, :target_task_id, :link_type],
                     name: "task_links_unique_link_index"
                   )

    drop_if_exists index(:task_links, [:target_task_id])

    drop_if_exists index(:task_links, [:source_task_id])

    drop constraint(:task_links, "task_links_source_task_id_fkey")

    drop constraint(:task_links, "task_links_target_task_id_fkey")

    drop table(:task_links)
  end
end
