defmodule Camelot.Repo.Migrations.AddAgentOutputSchemaByStage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agents) do
      add :output_schema_by_stage, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:agents) do
      remove :output_schema_by_stage
    end
  end
end
