defmodule Camelot.Repo.Migrations.AddPermissionDenials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      add :permission_denials, {:array, :map}, default: []
    end
  end

  def down do
    alter table(:sessions) do
      remove :permission_denials
    end
  end
end
