defmodule Camelot.Repo.Migrations.AddAllowedTools do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :allowed_tools, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:tasks) do
      remove :allowed_tools
    end
  end
end
