defmodule Camelot.Repo.Migrations.AddGithubAuth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :github_user_id, :text
      add :github_email_declined, :citext
    end

    create unique_index(:users, [:github_user_id], name: "users_unique_github_user_id_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:github_user_id],
                     name: "users_unique_github_user_id_index"
                   )

    alter table(:users) do
      remove :github_email_declined
      remove :github_user_id
    end
  end
end
