defmodule Camelot.Repo.Migrations.AddPrAutoFixAttempts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :pr_auto_fix_attempts, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:tasks) do
      remove :pr_auto_fix_attempts
    end
  end
end
