defmodule Camelot.Repo.Migrations.AddStageState do
  @moduledoc """
  Replaces status/previous_status with stage/state.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :stage, :text, default: "todo"
      add :state, :text, default: "queued"
    end

    flush()

    execute("""
    UPDATE tasks SET stage = CASE status
      WHEN 'created' THEN 'todo'
      WHEN 'planning' THEN 'planning'
      WHEN 'needs_input' THEN 'planning'
      WHEN 'plan_review' THEN 'planning'
      WHEN 'executing' THEN 'executing'
      WHEN 'pr_created' THEN 'pr'
      WHEN 'pr_review' THEN 'pr'
      WHEN 'pr_fix' THEN 'pr'
      WHEN 'done' THEN 'done'
      WHEN 'cancelled' THEN 'cancelled'
    END
    """)

    execute("""
    UPDATE tasks SET state = CASE status
      WHEN 'created' THEN 'queued'
      WHEN 'planning' THEN 'in_progress'
      WHEN 'needs_input' THEN 'waiting_for_input'
      WHEN 'plan_review' THEN 'waiting_for_input'
      WHEN 'executing' THEN 'in_progress'
      WHEN 'pr_created' THEN 'waiting_for_input'
      WHEN 'pr_review' THEN 'waiting_for_input'
      WHEN 'pr_fix' THEN 'queued'
      WHEN 'done' THEN NULL
      WHEN 'cancelled' THEN NULL
    END
    """)

    alter table(:tasks) do
      modify :stage, :text, null: false, default: "todo"
      remove :status
      remove :previous_status
    end
  end

  def down do
    alter table(:tasks) do
      add :status, :text, default: "created"
      add :previous_status, :text
    end

    flush()

    execute("""
    UPDATE tasks SET status = CASE stage
      WHEN 'todo' THEN 'created'
      WHEN 'planning' THEN CASE state
        WHEN 'waiting_for_input' THEN 'plan_review'
        ELSE 'planning'
      END
      WHEN 'executing' THEN 'executing'
      WHEN 'pr' THEN CASE state
        WHEN 'queued' THEN 'pr_fix'
        ELSE 'pr_review'
      END
      WHEN 'done' THEN 'done'
      WHEN 'cancelled' THEN 'cancelled'
    END
    """)

    alter table(:tasks) do
      modify :status, :text, null: false, default: "created"
      remove :stage
      remove :state
    end
  end
end
