defmodule Camelot.Repo.Migrations.AddSessionProgress do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      add :progress_phase, :text
      add :progress_message, :text
      add :progress_at, :utc_datetime
    end
  end

  def down do
    alter table(:sessions) do
      remove :progress_at
      remove :progress_message
      remove :progress_phase
    end
  end
end
